version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./server:/app
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
     - CHOKIDAR_USEPOLLING=true
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"